# Generated by Django 4.2.30 on 2026-07-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricealert',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='date_closed',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='exit_price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='asset',
            name='change_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('forex', 'Forex'), ('stock', 'Stock')], default='crypto', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='condition',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='direction',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_tier',
            field=models.CharField(default='free', max_length=50),
        ),
    ]
