# Generated by Django 4.2.30 on 2026-07-27 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_pricealert_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITradingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strategy_type', models.CharField(choices=[('EVEN_ODD', 'Even / Odd Probability'), ('OVER_UNDER', 'Over / Under Threshold'), ('MATCH_DIFF', 'Match / Differ Pattern')], max_length=20)),
                ('min_confidence', models.FloatField(default=70.0)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='digit_precision',
            field=models.IntegerField(default=2, help_text='Decimals for digit analysis'),
        ),
        migrations.AddField(
            model_name='trade',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='payout',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trade',
            name='stake',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trade',
            name='target_digit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('forex', 'Forex'), ('stock', 'Stock'), ('synthetic', 'Synthetic Index')], default='crypto', max_length=20),
        ),
        migrations.CreateModel(
            name='PriceTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('last_digit', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='store.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
