# Generated by Django 4.2.30 on 2026-07-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_aitradingstrategy_asset_digit_precision_and_more'),
    ]

    operations = [
    ]
