# Generated by Django 4.2.30 on 2026-07-27 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20260727_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-date_opened']},
        ),
        migrations.AlterField(
            model_name='aitradingstrategy',
            name='strategy_type',
            field=models.CharField(choices=[('EVEN_ODD', 'Even / Odd Probability'), ('OVER_UNDER', 'Over / Under Threshold'), ('MATCH_DIFF', 'Match / Differ Pattern'), ('SENTIMENT_NLP', 'News Sentiment NLP (FinBERT)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pricetick',
            name='last_digit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='direction',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('WON', 'Won'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
        migrations.CreateModel(
            name='SentimentSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_symbol', models.CharField(default='XAU/USD', max_length=20)),
                ('query', models.CharField(max_length=255)),
                ('composite_score', models.FloatField()),
                ('signal', models.CharField(choices=[('BUY', 'Bullish / Buy'), ('SELL', 'Bearish / Sell'), ('NEUTRAL', 'Neutral / Hold')], max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('articles_analyzed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_signals', to='store.asset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=1000)),
                ('published', models.CharField(blank=True, max_length=100, null=True)),
                ('sentiment', models.CharField(max_length=20)),
                ('polarity', models.FloatField()),
                ('sentiment_signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='store.sentimentsignal')),
            ],
        ),
    ]
