# Generated by Django 4.2.30 on 2026-07-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_trade_options_and_more'),
    ]

    operations = [
    ]
