# Generated by Django 4.2.30 on 2026-07-27 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_add_created_at_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(choices=[('DERIV', 'Deriv Account'), ('PEPPERSTONE_MT5', 'Pepperstone MetaTrader 5'), ('PEPPERSTONE_CTRADER', 'Pepperstone cTrader')], default='DERIV', max_length=50)),
                ('account_number', models.CharField(max_length=100)),
                ('server_name', models.CharField(blank=True, default='Deriv-Server', max_length=100, null=True)),
                ('api_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
