# Generated by Django 4.2.30 on 2026-07-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_transaction_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='method',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='type',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_method',
            field=models.CharField(default='M-Pesa', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='request_type',
            field=models.CharField(default='DEPOSIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
