# Generated by Django 4.2.30 on 2026-07-31 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_paymentrequest_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='request_type',
            new_name='transaction_type',
        ),
    ]
