# Generated by Django 4.2.30 on 2026-08-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_request_type_paymentrequest_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
