# Generated by Django 4.2.30 on 2026-08-02 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0014_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], max_length=10)),
                ('url', models.URLField()),
                ('method', models.CharField(default='POST', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('requests_count', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=100.0)),
                ('latency', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
