# Generated by Django 4.2.30 on 2026-08-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_webhookendpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_trade_amount', models.DecimalField(decimal_places=2, default=10.0, help_text="Stake used for a trade when the trader doesn't specify one.", max_digits=12)),
                ('min_trade_amount', models.DecimalField(decimal_places=2, default=1.0, help_text='Smallest stake a trader is allowed to place.', max_digits=12)),
                ('max_trade_amount', models.DecimalField(decimal_places=2, default=1000.0, help_text='Largest stake a trader is allowed to place.', max_digits=12)),
                ('payout_percentage', models.DecimalField(decimal_places=2, default=90.0, help_text='House payout on a winning trade. 90.00 means a $10 winning stake returns $19.00 total (stake + 90% profit).', max_digits=5)),
                ('trading_enabled', models.BooleanField(default=True, help_text='Site-wide kill switch. Turn off to pause all new trade execution.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
