# Generated by Django 4.2.30 on 2026-08-19 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0021_fundedaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='provider_reference',
            field=models.CharField(blank=True, help_text='Ref ID from payment provider', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='pnl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_method',
            field=models.CharField(help_text='e.g., M-Pesa, BTC, USDT', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trade',
            name='direction',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stake',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Custom name for bot instance', max_length=100)),
                ('config_json', models.JSONField(default=dict, help_text='Bot strategy parameters')),
                ('state_json', models.JSONField(default=dict, help_text='Current running state of the bot')),
                ('is_running', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='user_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='store.userbot'),
        ),
    ]
