# Generated by Django 4.2.30 on 2026-08-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_account_updated_at_paymentrequest_provider_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
