# Generated by Django 4.2.30 on 2026-08-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_userprofile_is_active_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='transaction_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_trade_amount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='max_trade_amount',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='min_trade_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='payout_percentage',
            field=models.DecimalField(decimal_places=2, default=90.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='trading_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=50),
        ),
    ]
