# Generated by Django 4.2.30 on 2026-08-30 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0027_transactionlog_tradingaccount_tradeposition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycprofile',
            name='document_image',
        ),
        migrations.RemoveField(
            model_name='kycprofile',
            name='document_number',
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_selfies/'),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='document_type',
            field=models.CharField(default='National ID', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
