# Generated by Django 4.2.30 on 2026-08-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_kycprofile_document_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
