# Generated by Django 4.2.30 on 2026-09-08 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0031_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundedTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(default='XAUUSD', max_length=20)),
                ('direction', models.CharField(max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('lot_size', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('profit_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('profit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('funded_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='store.fundedaccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
