# Generated by Django 4.2.30 on 2026-09-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_fundedtrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='sl',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Stop Loss price', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='tp',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Take Profit price', max_digits=18, null=True),
        ),
    ]
