# Generated by Django 4.2.30 on 2026-09-10 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_trade_sl_trade_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbrokeraccount',
            name='last_balance_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='userbrokeraccount',
            name='last_known_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cached balance from last successful sync', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='userbrokeraccount',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbrokeraccount',
            name='sync_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbrokeraccount',
            name='sync_status',
            field=models.CharField(choices=[('OK', 'OK'), ('ERROR', 'Error'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='userbrokeraccount',
            name='broker',
            field=models.CharField(choices=[('DERIV', 'Deriv Account'), ('PEPPERSTONE_MT5', 'Pepperstone MetaTrader 5'), ('PEPPERSTONE_CTRADER', 'Pepperstone cTrader'), ('BINANCE', 'Binance Spot')], default='DERIV', max_length=50),
        ),
        migrations.CreateModel(
            name='BrokerBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='store.userbrokeraccount')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
